import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],


  // But you can create a sidebar manually
  landingApi: [
    {
      type: 'category',
      label: 'Authentication',
      items: ['landing/authentication/sign_in'],
    },
    {
      type: 'category',
      label: 'Product',
      items: ['landing/product/product_post'],
    },
  ],
};

export default sidebars;
